name: rdcli
description: Real-Debrid CLI.
version: 1.0.0
repository: https://github.com/tytydraco/rdcli

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  http: ^1.5.0
  json: ^0.20.4
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^9.0.0
